# modified from https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions
name: build the site

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install mkdocs and mike
        run: |
          pip install mkdocs-material
          pip install mike

      - name: Deploy with mike
        id: mikedeploy
        run: mike deploy --push --update-aliases ${{ github.event.inputs.version }} latest